GET http://localhost:3000/api/product

###

POST http://localhost:3000/api/product

{
    "name": "iPhone",
    "description": "Celular inteligente",
    "quantity": 4,
    "brand": "Apple",
    "ownerId": "12",
}